# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Дмитрий Черток
title: Backend developer
email: chertokdmitry@yandex.ru

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  chertokdmitry
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: dmitry-chertok-a840401a4
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Обо мне
about_profile_image: images/dmitry.jpeg
about_content: | # this will include new lines to allow paragraphs
  Привет, меня зовут Дмитрий, я бекэнд разработчик. Мой основной язык разработки PHP, а также я активно изучаю Go.
  Я работаю с базами данных SAP Sybase, MySql, Postgres, ElasticSearch.

  У меня есть опыт построения Rest API с помощью Swagger. В своем последнем проекте я разработал API с помощью GRPS Protobuf.

  В работе использую Gitlab, Jira, PhpStorm, Goland. Работаю в Linux, есть опыт настройки серверов.

content:
  - title: Проекты # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Телеграм-бот прогноза погоды
        link: https://t.me/surfweatherbot
        link_text: t.me/surfweatherbot
        # link_text: Project Website
        additional_links:
          - title: Главный сервис Телеграм-бота
            icon: fab fa-github
            url: github.com/chertokdmitry/surfbot
          - title:  API Protobuf GRPS
            icon: fab fa-github
            url: github.com/chertokdmitry/surfproto
          - title: Сервис производства видеороликов
            icon: fab fa-github
            url: github.com/chertokdmitry/surfavi
          - title: Сервис получения скриншотов камер
            icon: fab fa-github
            url: github.com/chertokdmitry/surfcams
          - title:  Rest API
            icon: fab fa-github
            url: github.com/chertokdmitry/surfapi
        quote: >
          Ссылки на репозитории с микросервисами проекта
        description: | # this will include new lines to allow paragraphs
          ![Схема сервиса](/images/surfweather.jpg "Схема сервиса")

          Телеграм бот показывает прогноз погоды на серф-спотах. Есть возможность посмотреть скриншот с камеры или видео за последние 24 часа. Можно подписаться и получать прогноз
          в определенное время каждый день. Проект состоит из 8 микросервисов написанных на GO. Взаимодействуют между собой через Rest API и GRPC API.

          В качестве источника данных используются Windy.com, Openweathermap.com. Данные сохраняются в базу Postgres.

          Технологии: <mark>Golang</mark> <mark>Postgres</mark> <mark>GRPC</mark>


  - title: Опыт # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Группа компаний «Эталон»
        link: http://www.lenspecsmu.ru
        link_text: lenspecsmu.ru
        sub_title: Backend Developer
        caption: Ноябрь 2019 - по настоящее время
        quote: >
          Группа «Эталон» сегодня является одной из крупнейших корпораций в сфере девелопмента и строительства в России.
        description: | # this will include new lines to allow paragraphs
          Разработка CRM, API, личного кабинета клиентов.
          Написание сложных запросов SQL к базе данных Sybase.
          Разработка с помощью Gitlab и CI flow, Jira.

          Технологии: <mark>SAP Sybase</mark> <mark>Laravel</mark> <mark>PHP</mark> <mark>jQuery</mark>
      - layout: left
        title: Инвестиционная Группа «ПКР»
        link: https://investprojects.info/
        link_text: investprojects.info
        sub_title: PHP-разработчик
        caption: Декабрь 2018 - ноябрь 2019
        quote: >
          Портал «Инвестиционные проекты» - цифровая платформа для поддержки инвестиционных проектов России и ЕАЭС.
        description: |
          Основные задачи в которых я принимал участие: развитие сайта, разработка API, разработка CRM для менеджеров, резервное копирование, репликация БД,
          настройка рабочих и тестовых серверов, настройка Gitlab CI.

          Технологии: <mark>YII 2</mark> <mark>MySQL</mark> <mark>Elasticsearch</mark> <mark>PHP</mark> <mark>Linux</mark>
      - layout: left
        title: Fashion Crystals
        sub_title: Программист PHP
        caption: Декабрь 2016 — ноябрь 2018
        quote: >
          Официальный представитель Swarovski AG в России.
        description: |
          Разработка внутренней CMS: обработка заказов, управление товарными остатками, отчетность и статистика, разработка новых модулей для внешнего сайта,
          администрирование выделенного сервера.

          Технологии: <mark>PHP 5.6</mark>, <mark>MySQL</mark>, <mark>jQuery</mark>, <mark>Bootstrap</mark>
  - title: Образование
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:
        caption: 1995 - 2000
        description: |
          Санкт-Петербургский государственный инженерно-экономический университет "ИНЖЭКОН"

          Экономики и менеджмента, Диплом

  - title: Повышение квалификации, курсы
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        caption: 2019
        description: |
          Framework Laravel
          Otus, Сертификат
      - layout: left
        caption: 2017
        description: |
          PHP-разработчик
          Otus, Сертификат
      - layout: left
        caption: 2015
        description: |
          PHP. Уровень 4. Проектирование и разработка сложных веб-проектов на PHP 5
          «Специалист» при МГТУ им Н.Э.Баумана, Сертификат
      - layout: left
        caption: 2011
        description: |
          Проектный менеджмент
          Высшая экономическая школа Университета экономики и финансов, Сертификат PMI
      - layout: left
        caption: 2010
        description: |
          Профессиональное программирование на PHP 5. ХМL и технология AJAX
          Петербургский государственный политехнический университет, Сертификат
  - title: Знание языков
    layout: text
    content: |
      Русский — Родной

      Английский — C1 — Продвинутый
  - title: Немного о хобби и увлечениях
    layout: text
    content: |
      Кроме программирования у меня есть несколько хобби:
      - Кайтсерфинг
      - Сноуборд
      - Большой теннис


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
